name: Manual Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"
      create_release:
        description: "Create GitHub release"
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # AMD64 builds
          - os: ubuntu-latest
            arch: amd64
            binary_name: smart-rds-viewer-linux-amd64
          # ARM64 builds
          - os: ubuntu-latest
            arch: arm64
            binary_name: smart-rds-viewer-linux-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          python build.py

      - name: Rename binary
        run: |
          cd dist
          if [ "${{ runner.os }}" = "Windows" ]; then
            mv smart-rds-viewer.exe ${{ matrix.binary_name }}
          else
            mv smart-rds-viewer ${{ matrix.binary_name }}
          fi

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: dist/${{ matrix.binary_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.create_release }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          files: |
            smart-rds-viewer-linux-amd64
            smart-rds-viewer-linux-arm64
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
