name: Release Build

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    outputs:
      binary-name: ${{ steps.rename.outputs.binary-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary for AMD64
        run: |
          # Ensure we're building for AMD64
          export ARCH=amd64
          python build.py

      - name: Rename binary
        id: rename
        run: |
          cd dist
          mv smart-rds-viewer smart-rds-viewer-linux-amd64
          echo "binary-name=smart-rds-viewer-linux-amd64" >> $GITHUB_OUTPUT

      - name: Upload AMD64 binary
        uses: actions/upload-artifact@v4
        with:
          name: smart-rds-viewer-linux-amd64
          path: dist/smart-rds-viewer-linux-amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm
    outputs:
      binary-name: ${{ steps.rename.outputs.binary-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary for ARM64
        run: |
          # Native ARM64 build - no emulation needed!
          export ARCH=arm64
          python build.py

      - name: Rename binary
        id: rename
        run: |
          cd dist
          mv smart-rds-viewer smart-rds-viewer-linux-arm64
          echo "binary-name=smart-rds-viewer-linux-arm64" >> $GITHUB_OUTPUT

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: smart-rds-viewer-linux-arm64
          path: dist/smart-rds-viewer-linux-arm64

  create-release:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get previous tag
        id: previous_tag
        run: |
          # Get the latest tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
          echo "📋 Previous tag: $PREVIOUS_TAG"

      - name: Calculate next version
        id: next_version
        run: |
          PREVIOUS_TAG="${{ steps.previous_tag.outputs.previous_tag }}"
          BUMP_TYPE="${{ inputs.bump_type }}"
          
          # Remove 'v' prefix and split version
          VERSION=${PREVIOUS_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Bump version based on type
          case $BUMP_TYPE in
            "major")
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            "minor")
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            "patch")
              PATCH=$((PATCH + 1))
              ;;
          esac
          
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "next_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "🚀 New version: $NEW_VERSION"

      - name: Create tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a ${{ steps.next_version.outputs.next_version }} -m "Release ${{ steps.next_version.outputs.next_version }}"
          git push origin ${{ steps.next_version.outputs.next_version }}

      - name: Download binaries
        uses: actions/download-artifact@v4

      - name: List downloaded files
        run: |
          echo "📁 Downloaded artifacts:"
          find . -name "smart-rds-viewer*" -type f
          echo "📁 Current directory contents:"
          ls -la

      - name: Move binaries to root
        run: |
          # Move binaries from subdirectories to root for easier access
          mv smart-rds-viewer-linux-amd64/smart-rds-viewer-linux-amd64 ./smart-rds-viewer-linux-amd64
          mv smart-rds-viewer-linux-arm64/smart-rds-viewer-linux-arm64 ./smart-rds-viewer-linux-arm64
          chmod +x smart-rds-viewer-linux-amd64 smart-rds-viewer-linux-arm64
          echo "✅ Binaries moved and made executable"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.next_version.outputs.next_version }}
          name: Release ${{ steps.next_version.outputs.next_version }}
          files: |
            smart-rds-viewer-linux-amd64
            smart-rds-viewer-linux-arm64
          body: |
            ## Smart RDS Viewer ${{ steps.next_version.outputs.next_version }}

            ### Downloads
            - **Linux AMD64**: `smart-rds-viewer-linux-amd64`
            - **Linux ARM64**: `smart-rds-viewer-linux-arm64`

            ### Usage
            ```bash
            # Make executable
            chmod +x smart-rds-viewer-linux-amd64

            # Run
            ./smart-rds-viewer-linux-amd64
            ```

            ### Requirements
            - AWS credentials configured
            - RDS, CloudWatch, and Pricing API permissions
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
